### ISSUE TITLE
Docs not showing code

### ISSUE THREAD

**Issue by justinxreese** [Eonasdan/bootstrap-datetimepicker#773] opened 2015-01-23 04:00 UTC
The documents aren't showing code samples anymore, I can only find it by inspecting the page
http://eonasdan.github.io/bootstrap-datetimepicker/

![image](https://cloud.githubusercontent.com/assets/150839/5869643/572abfb0-a28a-11e4-8e4f-bdc337c4bee8.png)

**Comment by Eonasdan** [comment] 2015-01-23 21:57
duplicate of #770

**Closed by Eonasdan** 2015-01-23 21:57 UTC
Labels: duplicate
