### ISSUE TITLE
Keybinds don't work when leaving focus while key pressed down

### ISSUE THREAD

**Issue by dutchmega** [Eonasdan/bootstrap-datetimepicker#1926] opened 2016-12-13 15:22 UTC
If you leave the picker while pressing down a key and go back to it, the keybinds don't work anymore.

The issue is that the keyState variable thinks a key is still pressed down, even when focus has changed. When focus comes back to the picker, keybinds are not executed because 2 keypresses are pressed down.

My fix is resetting keyState in the hide() method.

**Comment by moorthy28sep** [comment] 2017-01-19 06:45
Facing same issue. Looking for a preferred solution...

**Comment by j0cl** [comment] 2018-10-11 10:14
The keyState is not set to 'r' because the keyup event is not triggered for keys that hide the picker.
As #1782 points out, this seems to be caused by calling blur() in the hide function.

Indeed, this has the effect that on a subsequent opening of the picker, the code still interprets this as mutliple keys being in the pressed 'p' state and then failing to call the handler.

However, this issue seems to be a duplicate of #1883.

**Closed** 2020-11-12 20:46 UTC
