### ISSUE TITLE
should not check escaped characters inside moment format string

### ISSUE THREAD

**Issue by duknic** [Eonasdan/bootstrap-datetimepicker#1680] opened 2016-07-04 10:48 UTC
Trying to do something like:
`format: 'DD/MM/YYYY [at] HH:mm',`
But I think the format string is checked for contains 'a' or 'A' and the outcome of this check is then used to determine 12 or 24 hour functionality (i.e. whether the ui will display the AM/PM selector).

I want to work in 24hr time, without AM/PM selector and so have found I must omit the 'a' from my format string, which is not ideal.
`format: 'DD/MM/YYYY HH:mm',`

**Comment by William-H-M** [comment] 2017-10-03 14:27
Duplicate of #1645

**Closed by William-H-M** 2017-10-03 14:27 UTC
