### ISSUE TITLE
Linked Pickers 

### ISSUE THREAD

**Issue by kjmagic13** [Eonasdan/bootstrap-datetimepicker#1239] opened 2015-08-06 13:04 UTC
Since upgrading from 4.7.14 to 4.15.35 selecting the start picker of a linked picker pair automatically fills the end picker with today's date. This limits the maximum date of the start picker to today's date and requires a change of the end picker to adjust the start picker to a later time. This issue can be witnessed on the [demonstration page](http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers).

**Comment by Eonasdan** [comment] 2015-08-08 14:58
duplicate of #1075. I'll update the docs

**Comment by Eonasdan** [comment] 2015-08-08 15:34
added a note to the docs

**Closed by Eonasdan** 2015-08-08 15:34 UTC
Labels: Docs, question
