### ISSUE TITLE
minDate/maxDate not using format

### ISSUE THREAD

**Issue by tsjoberg** [Eonasdan/bootstrap-datetimepicker#1045] opened 2015-05-04 19:32 UTC
Hi,

I have noticed min/max date does not use the formatted moment but rather the moment object as-is:

Fiddle: http://jsfiddle.net/0Ltv25o8/920/

This does create some unwanted results if not working with specific time (dates for example) as string dates without time would fail before/after check due to the fact that default moment object will incorporate time. Creating moment object with only date string will create time as 00:00:00.

Not sure if this is expected or any min/max date setting should apply the provided format if provided

**Comment by Eonasdan** [comment] 2015-05-04 20:05
this is the expected behavior. Since `min/maxDate` can used to restrict the time element as well, it's up to you to provide what is "proper"

**Comment by tsjoberg** [comment] 2015-05-04 20:10
Understood but just a follow up question - isn't what I am providing for "proper" the format option on the initialize ?, then the picker can assume to use that format for any input dates that need to be parsed into a moment object?:

 ```format: "L"```

If you don't agree that is completely fine as well - just more of a question/comment.

Thanks!

**Comment by Eonasdan** [comment] 2015-05-07 20:05
Please vote on this issue. 

Reply with a plus 1 for an up vote indicating that min/max date will take the given `format` string

Reply with minus 1 for a down vote indicating that this should stay the same

**Comment by tsjoberg** [comment] 2015-05-07 20:10
:+1:  but I opened issue so I am biased :grinning:

**Comment by liammoat** [comment] 2015-05-14 09:54
+1

**Comment by less-anonymous** [comment] 2015-05-18 16:05
+1

**Comment by tsjoberg** [comment] 2015-05-18 16:17
Also not sure if this is desired but I think it would be better if the default format was used only when an input is not a moment object (string, date). If it is already a moment object I would argue to take the moment object as-is

**Comment by dukedelaet** [comment] 2015-05-21 16:59
+1

**Comment by LeonardHarley** [comment] 2015-05-22 18:41
+1

**Comment by Eonasdan** [comment] 2015-09-12 01:29
I can't figure out a good way to implement this without code smell. For now, this can be fixed by calling `startOf('d')` on your moment objects for `min/maxDate`

**Closed** 2020-11-12 20:52 UTC
Labels: v4
