### ISSUE TITLE
Start of the week option

### ISSUE THREAD

**Issue by Firzenizer** [Eonasdan/bootstrap-datetimepicker#1030] opened 2015-04-28 06:10 UTC
I was looking for an option to set start of the week and realized there wasn't such option. Could this be added? Noticed other people had been also looking for this option: 
http://stackoverflow.com/questions/24410685/bootstrap-3-datetimepicker-3-0-0-week-starts-at-monday

They ended up using dirty solutions to come around this issue.

**Comment by Eonasdan** [comment] 2015-04-28 13:46
Start of the week is based on the [`locale` provided](http://stackoverflow.com/a/24471814/237917). This is defined by moment's locales. If you want to change it, create your own locale file or override. [See moment's docs](http://momentjs.com/docs/#/i18n/).

Duplicate of #1013, #518, #345 and #670

**Closed by Eonasdan** 2015-04-28 13:46 UTC
