### ISSUE TITLE
TypeError: widget.find is not a function

### ISSUE THREAD

**Issue by jAddict7** [Eonasdan/bootstrap-datetimepicker#768] opened 2015-01-21 14:24 UTC
When we use month and year selector without days in it, getting a js error as **TypeError: widget.find is not a function**. Open firebug and check this [link](http://jsfiddle.net/0Ltv25o8/57/).

Thanks for this awesome plugin.

**Comment by Eonasdan** [comment] 2015-01-21 21:09
duplicate of #761

**Closed by Eonasdan** 2015-01-21 21:09 UTC
Labels: bug
