### ISSUE TITLE
Date Picker Is Not Showing Current Time by Default

### ISSUE THREAD

**Issue by kerry-money** [Eonasdan/bootstrap-datetimepicker#1144] opened 2015-06-23 20:54 UTC
In previous versions, when using date picker with a time, the current date and time would be shown by default. In newer versions (4.7.14 on), the time shown is 12:00 AM.  It looks like in previous versions the date and view date were initialized to the current moment, whereas now they are initialized to the start of the current day.

**Comment by pleepleus88** [comment] 2015-07-08 19:37
I am using 4.7.14, and not seeing this issue. Are you maybe setting the useCurrent option to false, or some other value? 

Looking at the source, valid values appear to be false, true, 'year', 'month', 'day', 'hour', or 'minute'. I would think true or 'minute' would get you what you're looking for. 

http://eonasdan.github.io/bootstrap-datetimepicker/Options/#usecurrent
(Note that 'year', 'month', 'day', 'hour', and 'minute' are not described in that help doc.)

**Comment by digitalfrost** [comment] 2015-09-13 16:32
This is a duplicate of  #1311

**Closed** 2017-08-26 23:44 UTC
