### ISSUE TITLE
[BUG] viewMode "decade"

### ISSUE THREAD

**Issue by JarekWichrowski** [Eonasdan/bootstrap-datetimepicker#1265] opened 2015-08-17 10:27 UTC
I'm set options:
$dateTimePicker.datetimepicker({
                    format: 'DD-MM-YYYY',
                    minDate: 01-01-2012,
                    maxDate: 01-01-2015
                });

If I see "decade" view I don't select decade item and i not come back to "years" view all decade item is disabled

**Comment by Eonasdan** [comment] 2015-08-17 13:28
duplicate of #1170

**Closed by Eonasdan** 2015-08-17 13:28 UTC

**Comment by davidhathaway** [comment] 2015-08-27 12:17
I had the same issue, it was a little annoying because you could get the control into a state where it was stuck on the decades screen.

I think it was because ```isValid``` not taking the range into account. 

So i added this function to check if the decade range overlapped the min / max range. (i've added moment-range,js)

```javascript

isValidDecade = function (targetMoment)
            {
                if (options.minDate && options.maxDate)
                {
                    var optionsRange = moment.range(options.minDate, options.maxDate);
                    var targetRange = moment.range(targetMoment, targetMoment.clone().add(12, 'y'));
                    return targetRange.overlaps(optionsRange);
                }
                else {
                    return isValid(targetMoment, 'y');
                }  
            },


 updateDecades = function () {
....

 while (!startDecade.isAfter(endDecade, 'y')) {
                    html += '<span data-action="selectDecade" class="decade' + (startDecade.isSame(date, 'y') ? ' active' : '') +
                        (!isValidDecade(startDecade) ? ' disabled' : '') + '" data-selection="' + (startDecade.year() + 6) + '">' + (startDecade.year() + 1) + ' - ' + (startDecade.year() + 12) + '</span>';
                    startDecade.add(12, 'y');
                }

....

}

```

I think this part needs tweaked also so the current date decade is pre-selected but its doesn't bother me at the minute - ```(startDecade.isSame(date, 'y') ? ' active' : '')```
