### ISSUE TITLE
from version 4.17.42 min view mode case not working correctly

### ISSUE THREAD

**Issue by akrom123** [Eonasdan/bootstrap-datetimepicker#1914] opened 2016-12-05 15:27 UTC
you may compare minViewMode case
on version 4.17.37 https://codepen.io/anon/pen/WozpoY
and on version 4.17.42 https://codepen.io/anon/pen/KNoWqL

**Comment by DominoDev** [comment] 2016-12-05 20:30
this looks like a duplicate of #[1894](https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1894)

**Comment by pascal-hofmann** [comment] 2017-01-11 13:32
Which itself is a duplicate of #1854.

**Closed** 2017-08-17 04:57 UTC
