### ISSUE TITLE
While choosing a new date, time shouldn't be changed

### ISSUE THREAD

**Issue by PoslinskiNet** [Eonasdan/bootstrap-datetimepicker#1884] opened 2016-11-15 12:59 UTC
Hello,

I've encounter the problem with **eonasdan-bootstrap-datetimepicker** and **moment 2.16.0**. I've tried a few versions of Moment already. It was working well with older Moments and **Ember** bellow **2.8.0**. I had to upgrade this package because of a new version of jQuery in Ember (3.x). 

The problem is: while changing a date, the time is always set to the current time. Even if I've changed the time, and go back to the calendar - time will be overwritten. Besides that, other behaviours work fine. 

Any thoughts, any ideas?

Thanks in advance for any help.

**Comment by outshyn** [comment] 2016-11-17 01:47
Just to assist PoslinskiNet & dev team, here is what I experienced.

Created a field with a datetimepicker.  Pre-fill field with a date & time.  Click the datetimepicker icon to show calendar.  Select the time option and change time.  Good.  Click away from field.  Click back to datetimepicker icon, change date.  Date changes, time is maintained.  Good!

HOWEVER, now try same steps without clicking away from field.  Like this.  Upon initial display of page, click datetimepicker icon to show calendar.  Select a new date.  Watch as date changes (good) but then time is adjusted!  For me, the time does not appear to change to current time -- if I have multiple fields with multiple datetimepickers, each field will get its own, random time if I click on a new date.

So it appears that something is not *initially* picking up the field, but after using the interface to change the time, everything is maintained OK from there on out.

**Comment by karolyi** [comment] 2016-11-22 16:09
+1, can confirm.

when initializing a datetimepicker with only a date format (so time picker is unnecessary), it will always set its time to the initialization time on choosing a date.

then, after the picker closed, clicking again on the input field which brings up the datetimepicker again, executes a `dp.change` event, showing the initialization time as the `event.oldDate`'s  time.

currently trying to find ways to mitigate this issue without modifying the source.

**Comment by karolyi** [comment] 2016-11-22 17:52
after hours of investigation, here's the root of problem:

when initializing the widget at https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L2343, the widget initializes with the actual moment, that contains the hours, minute and seconds resolution.

when changing the date by picking another one, `selectDay` (https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L1027-L1039) manipulates that date, ignoring the `YYYY-MM-DD` format.

so, when I assign a certain date that contains a different `HH:MM:SS`, the `dp.change` will always fire because the widget has another one. as I only use `YYYY-MM-SS` resolution, I set the time to `00:00:00` when changing from the outside. hence, `dp.change` will fire when it sees that the contained date is different in terms of `HH:MM:SS`.

workaround until this will be fixed: if you change the date from outside by using `date`, always use the `HH:MM:SS` that datetimepicker has been initialized with. thus, `dp.change` won't fire when you choose the same date OR open the picker.

(massive facepalms, btw)

I don't know who's responsible for fixing this, but please do fix this.

**Comment by karolyi** [comment] 2016-11-22 18:10
Better, easier workaround:

when changing the picker's date from the outside, don't just use `date(momentInstance)`, but also `viewDate(momentInstance)`.

this will set the widgets inner stored date to the desired `HH:MM:SS`, so you won't get `dp.change` double fires when changing the date or opening the picker by clicking/focusing on it.

**Comment by razorcd** [comment] 2016-12-09 00:03
another simple BUG example:
https://jsfiddle.net/66xnfex3/2/

**Comment by razorcd** [comment] 2016-12-12 11:28
This should be marked as a CRITICAL bug. It's breaking usability of this datetimepicker.

**Comment by benjiew** [comment] 2017-01-06 13:17
I'm getting the same behaviour with 'LT' format - when changing a time, the date part is updating to the current date.

**Comment by valeriob** [comment] 2017-10-02 12:25
Any update on this one ?

**Comment by William-H-M** [comment] 2017-10-02 12:37
Hi, non of the OP and the one of @razorcd was able to reproduce it on the latest version.
@valeriob can you test it out on your own and see if still happen as following the steps given above didn't seem to happen to me, thanks.

https://jsfiddle.net/William_/20oywuno/

**Comment by valeriob** [comment] 2017-10-02 12:52
I'm updating the package in our solution right now since we are not able to reproduce it on 4.15.45.

**Comment by William-H-M** [comment] 2017-10-02 13:02
Hi, the latest version, 4.17.47, doesn't have this error. So I'll be closing this.

**Closed by William-H-M** 2017-10-02 13:02 UTC

**Comment by PoslinskiNet** [comment] 2017-10-02 16:30
It works 👍

**Comment by carlituxman** [comment] 2017-12-22 12:59
I have 4.17.47 and has the error:

moment-with-locales.min.js:1 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format.....

**Comment by William-H-M** [comment] 2017-12-22 13:11
@carlituxman this is not an error is a deprecation warning as it says, update your moment.js and don't use string formats like: "12-25-1995" use moment("12-25-1995", "MM-DD-YYYY");

http://momentjs.com/docs/#/parsing/string/
