### ISSUE TITLE
optional label for showClose button

### ISSUE THREAD

**Issue by conceptualspace** [Eonasdan/bootstrap-datetimepicker#1417] opened 2016-01-09 21:36 UTC
the 'showClose' option renders a single "X" icon on the bottom toolbar, which might confuse some users into thinking it clears/deletes their date selection rather than merely closing the picker

suggest adding an optional label to show with the icon, ex, `'showCloseLabel: "done"`

**Comment by pgifford** [comment] 2016-04-20 14:06
Effectively a duplicate of #1285

**Closed** 2017-09-01 16:01 UTC
