### ISSUE TITLE
'Select time' title to select date

### ISSUE THREAD

**Issue by inad9300** [Eonasdan/bootstrap-datetimepicker#1800] opened 2016-09-23 11:43 UTC
To select the time, you have to click a button whose title is 'Select time'. To go back to select the date, you have to click a button whose title is 'Select time' again. It would be good to change this.

You can find the problem in the code in: https://github.com/Eonasdan/bootstrap-datetimepicker/blob/295db971685cc68a72990b3b5385e7c25a3ecd90/src/js/bootstrap-datetimepicker.js#L314, where the value of the title is fixed no matter the real action performed.

**Comment by William-H-M** [comment] 2017-10-04 12:56
Duplicate of #1542

**Closed by William-H-M** 2017-10-04 12:56 UTC
