### ISSUE TITLE
Datetimepicker coming behind div with position fixed

### ISSUE THREAD

**Issue by nosheen-javed** [Eonasdan/bootstrap-datetimepicker#1863] opened 2016-11-01 11:20 UTC
I have a static header and when i scroll to end, datetimepicker opens to the top but behind the header. Is there any way we can set the z-index of the datetimepicker widget?

Thanks.

![image](https://cloud.githubusercontent.com/assets/23119591/19888216/7ff26af6-9fea-11e6-8e68-7705bad4eed8.png)

**Comment by agentili** [comment] 2016-11-03 08:40
I have a similar problem in a complex page. Trying the classic datepicker of jquery instead the problem is not there.
All the parent divs have relative position but the widget seems close into the first parent.

Following the discussion and thanks in advance

**Comment by nosheen-javed** [comment] 2016-11-07 05:55
I actually want the time picker as well. So i do not see any better time picker. Do you know any better time picker i can use instead of this?
Thanks

**Comment by leekay0032** [comment] 2018-01-16 10:45
"top": "auto", "bottom": "auto", "left": "auto", "right": "auto", "position": "fixed"

**Comment by wolgan09** [comment] 2018-02-19 15:27
According to the script of none of the parent should be set fixed.
Due to the parent's fixed position it might set the datetimepicker's position fixed also.

Code from jquery.datetimepicker.full.min.js :
put a debug point here , this might help you resolve the position issue  
return "fixed" === F.contentWindow.getComputedStyle(e).getPropertyValue("position") ? (s = !0,
                    !1) : void 0

Please check again for the fixed position which might be causing this issue. I had same problem and resolved by setting the parent position to absolute.

**Comment by lyndonjohn** [comment] 2018-07-12 07:02
I had the same issue. I solved it by creating a custom css file and gave datepicker a new z-index.

```
.datepicker.dropdown-menu {
    z-index: 9999 !important;
}
```

**Comment by deeksha92** [comment] 2018-08-10 13:26
Hi,
I'm also facing the same issue. Can someone help me with the same.

**Comment by ewirth** [comment] 2018-10-28 23:34
> 
> 
> I had the same issue. I solved it by creating a custom css file and gave datepicker a new z-index.
> 
> ```
> .datepicker.dropdown-menu {
>     z-index: 9999 !important;
> }
> ```

lyndonjohn's answer should work since:
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css :
.navbar-fixed-top{position:fixed;right:0;left:0;z-index:1030}

**Comment by uldisv** [comment] 2019-02-03 11:58
> I had the same issue. I solved it by creating a custom css file and gave datepicker a new z-index.
> 
> ```
> .datepicker.dropdown-menu {
>     z-index: 9999 !important;
> }
> ```

Great workaround.

**Comment by sfandrew** [comment] 2019-04-18 23:41
same with datetime picker

```
.bootstrap-datetimepicker-widget.dropdown-menu {
    z-index: 9999 !important;
}
```

**Comment by rochiey** [comment] 2019-12-18 08:52
> .bootstrap-datetimepicker-widget.dropdown-menu {
>     z-index: 9999 !important;
> }
is not working in accordion
![image](https://user-images.githubusercontent.com/38701913/71070999-c587d780-21b6-11ea-91f6-50895d882139.png)

i used datetimepicker

**Comment by cwills** [comment] 2020-01-25 20:09
I had to use javascript to add and remove style overflow="visible" when I clicked to expand and contract the accordion menu I was using.

document.getElementById("name-of-div").style.overflow = "visible";

**Comment by kprajaguru** [comment] 2020-04-29 21:04
> > .bootstrap-datetimepicker-widget.dropdown-menu {
> > z-index: 9999 !important;
> > }
> 
> is not working in accordion. See:
> ![image](https://user-images.githubusercontent.com/38701913/71070999-c587d780-21b6-11ea-91f6-50895d882139.png)
> 
> i used datetimepicker

Am also facing a similar issue! Did you happen to find a resolution to this accordion issue? Can you please help?

**Comment by chupetoide** [comment] 2020-06-24 18:25
Same issue here. Version 4.17. 47

**Comment by CHOUKI-Mouhssine** [comment] 2020-09-15 17:18
worked for me
.bootstrap-datetimepicker {
        z-index: 9999 !important;
    }

**Comment by rochiey** [comment] 2020-09-18 00:12
> > > .bootstrap-datetimepicker-widget.dropdown-menu {
> > > z-index: 9999 !important;
> > > }
> > 
> > 
> > is not working in accordion. See:
> > ![image](https://user-images.githubusercontent.com/38701913/71070999-c587d780-21b6-11ea-91f6-50895d882139.png)
> > i used datetimepicker
> 
> Am also facing a similar issue! Did you happen to find a resolution to this accordion issue? Can you please help?

No, I scrapped my project and make a hiding div with jquery hide and show than using accordion.

**Closed** 2020-11-12 20:46 UTC
Labels: v4
