### ISSUE TITLE
How to show only month

### ISSUE THREAD

**Issue by dungphanxuan** [Eonasdan/bootstrap-datetimepicker#1897] opened 2016-11-23 04:03 UTC
I set  'viewMode' => "months" . So firt select, only month will show, then next select, date will show.
Now i need next select only show month.

**Comment by jiboule** [comment] 2016-12-02 14:36
I got the same error here !

**Comment by pascal-hofmann** [comment] 2017-01-11 13:33
Duplicate of #1854.

**Comment by dungphanxuan** [comment] 2017-01-12 02:13
Here my code, i set event hide then set mode month again
```javascript
$('#w1').datetimepicker({"useCurrent":true,"locale":"ja","format":"YYYY-MM","defaultDate":"2017-01","minDate":new Date("2016-01"),"allowInputToggle":false,"sideBySide":true,"viewMode":"months","widgetPositioning":{"horizontal":"auto","vertical":"auto"}})
```
next set event 
```javascript
$('#w1').on('dp.hide', function(event){
  setTimeout(function(){
    $('#w1').data('DateTimePicker').viewMode('months');
  },1);
});
```

**Closed** 2017-08-17 05:01 UTC
