### ISSUE TITLE
viewMode not remembered

### ISSUE THREAD

**Issue by phippster** [Eonasdan/bootstrap-datetimepicker#1820] opened 2016-10-06 22:28 UTC
Initializing with:

```
viewMode: 'years',
format: 'YYYY-MM-DD',
useCurrent: false,
allowInputToggle: true,
```

I'm using useCurrent: false so that if the user does NOT click on anything within the picker (e.g. clicks off the picker to close it) that the default current date will not be entered into the field.  

With the viewMode setting the picker should open into the "years" mode as set.  The first time it is opened this is true:
![screen shot 2016-10-06 at 3 25 45 pm](https://cloud.githubusercontent.com/assets/1810557/19172942/66f01dc0-8bd9-11e6-9ec7-66b10de85578.png)

The second time (any subsequent times the picker is opened) the viewMode is NOT respected EVEN though there is no date in the field:
![screen shot 2016-10-06 at 3 25 51 pm](https://cloud.githubusercontent.com/assets/1810557/19172947/6b7a3de4-8bd9-11e6-8e31-94390467a36b.png)

ViewMode should be respected as long as no date has been selected.

**Comment by bjsafdie** [comment] 2016-10-08 13:27
I also see this issue. It seems to be related to 4.17.42.  I have a Knockout Component wrapper for the DateTimePicker.  It works fine on 4.15.35:

> http://codepen.io/bjsafdie/pen/ee515a6e09e5fb268132c71e7dcfb2d4

When I updated to 4.17.42, I see the behavior described above.

> http://codepen.io/bjsafdie/pen/e83f73514dc2da44325aeb12b3615b10

Unlike phippster, I am using `viewMode: 'months'` and `format: 'MMM, YYYY'` -- no Days in the format.  However, the days view is still shown after the first picker opening.

**Comment by tungel** [comment] 2016-10-11 00:00
It seems related to https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1783 too.

**Comment by xyluet** [comment] 2016-10-14 06:48
so what i have to do ?

**Comment by iamdriz** [comment] 2016-10-14 14:23
This isn't related to `useCurrent: false` as I have removed this option and still see the issue on the second time the picker is opened. Hopefully a fix will be in place soon.

**Comment by iamdriz** [comment] 2016-10-14 14:33
Also check the options with `$('#Months').data('DateTimePicker').options();` reveals that the `viewMode` is still correct but that the picker itself doesn't honour it!

**Comment by iamdriz** [comment] 2016-10-14 14:41
Is their a short term fix that can be applied to solve this until a patch is created?

**Comment by iamdriz** [comment] 2016-10-14 14:45
One fix that does work is to reset the viewMode (even though the option is correct already) when the picker is closed. e.g.
~~~
$('#Years').on('dp.hide', function(event){
          $('#Years').data('DateTimePicker').viewMode('years');
        });
~~~

**Comment by xyluet** [comment] 2016-10-15 04:15
^
thanks, I'll give a try

**Comment by ralitsaradeva** [comment] 2016-10-19 12:13
Same here, it doesn't work for me as well.
From what I saw, the issue is with 
`currentViewMode = 0;` at the end of the `hide` function.
Instead it should be:
`currentViewMode = minViewModeNumber;`

**Comment by fzanollo** [comment] 2016-10-20 14:26
+1 to this issue, I have this:

```
$('#selector').datetimepicker({
    locale: "es",
    format: "MM-YYYY",
    viewMode: "years"
});
```

it lets you pick year and month the first time but if clicked again it shows the complete date calendar picker (although if you click a day it doesn't change the input as format only recognizes months and years)

**Comment by mvpkenlin** [comment] 2016-11-02 09:06
solution in https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1850

**Comment by William-H-M** [comment] 2017-08-18 12:41
Hi, this was solved on latest version.
https://jsfiddle.net/William_/ja6v6x2x/

**Closed by William-H-M** 2017-08-18 12:41 UTC
