### ISSUE TITLE
How to highlight certain dates?

### ISSUE THREAD

**Issue by zairnamlas** [Eonasdan/bootstrap-datetimepicker#1024] opened 2015-04-24 11:23 UTC
How to highlight (having different background color or etc.,) for some dates only?
It will be better if that works whenever we change the month too so other month's date can participate as well.

**Comment by Eonasdan** [comment] 2015-04-24 14:43
duplicate of #1006 

this has been requested in #841 (v5 planning). Currently, there isn't an out of the box function for this.

If you use the dev branch, it includes a `data-day-` on the `td` of in the datepicker. Unfortunately, you'll have to do this any time the month view changes.

**Closed by Eonasdan** 2015-04-24 14:43 UTC
