### ISSUE TITLE
How to disable previous date selection

### ISSUE THREAD

**Issue by zitengine** [Eonasdan/bootstrap-datetimepicker#2231] opened 2018-02-21 18:31 UTC
Hi I have removed the Value From this. Its shows current date only on clink on the icon and can select previous date. I want to disable select previous date. for example today is [ 22 Jan 2018 ] HE can select after [ 24 jan 2018] No date before this can not be selected
I use momnet js  also. Please help
```
			<!-- input with datetimepicker -->
			<div class="form-group">
			    <label class="label-control">Datetime Picker</label>
			    <input type="text" class="form-control datetimepicker" value="10/05/2016"/>
			</div>

			<!-- javascript for init -->
			    $('.datetimepicker').datetimepicker({
			    icons: {
			        time: "fa fa-clock-o",
			        date: "fa fa-calendar",
			        up: "fa fa-chevron-up",
			        down: "fa fa-chevron-down",
			        previous: 'fa fa-chevron-left',
			        next: 'fa fa-chevron-right',
			        today: 'fa fa-screenshot',
			        clear: 'fa fa-trash',
			        close: 'fa fa-remove'
			    }
			});
```

**Comment by William-H-M** [comment] 2018-02-21 19:22
Duplicate of #2230

**Closed by William-H-M** 2018-02-21 19:22 UTC
