### ISSUE TITLE
showTodayButton set the current date and time but doesn't set the calandar view if month has been changed

### ISSUE THREAD

**Issue by sdespont** [Eonasdan/bootstrap-datetimepicker#1928] opened 2016-12-14 07:40 UTC
'Today' button set the right date and time, but doesn't switch view to the current day if the month has been changed at least in version 4.17.43.
 
Here is a fiddle to show the problem : https://jsfiddle.net/0Ltv25o8/4229/

To reproduce:
1. Select a date in another month (next or previous month for example)
2. Click on the "Go to today" button => The current date and time is set in the input field (OK), the time is set to the current time (OK), but the calandar view is not displaying the current date which is now selected (KO)

**Comment by hackel** [comment] 2016-12-30 18:02
Dupe of #1831.

**Comment by sdespont** [comment] 2016-12-31 15:41
Fixed with version 4.17.44

Updated fiddle : https://jsfiddle.net/0Ltv25o8/4384/

**Closed** 2017-08-17 04:57 UTC
