### ISSUE TITLE
input element still have "focus" event listener when destroy

### ISSUE THREAD

**Issue by Giangdv** [Eonasdan/bootstrap-datetimepicker#2121] opened 2017-06-09 08:06 UTC

**Comment by dicastro** [comment] 2017-08-16 10:58
I have the same problem.

If the datetimepicker is destroyed and recreated several time, each time an additional '' element is shown.

I think that the problem is in the method `detachDatePickerElementEvents`. After looking at the opposite one `attachDatePickerElementEvents`, I have realized that is not exactly the inverse.

```
attachDatePickerElementEvents = function () {
    input.on({
        'change': change,
        'blur': options.debug ? '' : hide,
        'keydown': keydown,
        'keyup': keyup,
        'focus': options.allowInputToggle ? show : ''
    });

    if (element.is('input')) {
        input.on({
            'focus': show
        });
    } else if (component) {
        component.on('click', toggle);
        component.on('mousedown', false);
    }
}
```

What I've done to solve this is to modify the method `detachDatePickerElementEvents` from:

```
detachDatePickerElementEvents = function () {
    input.off({
        'change': change,
        'blur': blur,
        'keydown': keydown,
        'keyup': keyup,
        'focus': options.allowInputToggle ? hide : ''
    });

    if (element.is('input')) {
        input.off({
            'focus': show
        });
    } else if (component) {
        component.off('click', toggle);
        component.off('mousedown', false);
    }
}
```

to:

```
detachDatePickerElementEvents = function () {
    input.off({
        'change': change,
        'blur': options.debug ? '' : hide,
        'keydown': keydown,
        'keyup': keyup,
        'focus': options.allowInputToggle ? show : ''
    });

    if (element.is('input')) {
        input.off({
            'focus': show
        });
    } else if (component) {
        component.off('click', toggle);
        component.off('mousedown', false);
    }
}
```

**Comment by William-H-M** [comment] 2018-03-13 16:07
Hi, I’ll be closing issues that have been answered by the community.

**Closed by William-H-M** 2018-03-13 16:07 UTC
