### ISSUE TITLE
enabledDates with array of string

### ISSUE THREAD

**Issue by GitzJoey** [Eonasdan/bootstrap-datetimepicker#2203] opened 2017-11-08 13:15 UTC
hi,

it seem i cant make enabledDates working with array of string
please check this [fiddle](http://jsfiddle.net/0Ltv25o8/5866/)

**Comment by William-H-M** [comment] 2017-11-08 15:53
Hi, actually **IT'S working**, but not as you are expecting to, if you check July month you will see there your date, Why? Simple if you check your console on your browser you will se a beautiful alert from moments.js for the latest version saying this:

> "Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
> Arguments: 
> [0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 07/11/2017, _f: undefined, _strict: false, _locale: [object Object]
> x/<@https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js:6:3248
> gb@https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js:6:19734
> rb@https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js:6:22824
> qb@https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js:6:22691
> pb@https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js:6:22410
> sb@https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js:6:23150
> tb@https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js:6:23184
> a@https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js:6:199
> y@https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js:1:1363
> da@https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js:1:16347
> na/<@https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js:1:21184
> each@https://code.jquery.com/jquery-2.2.4.js:365:10
> na@https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js:1:21158
> c/l.enabledDates@https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js:1:24321
> c/l.options/<@https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js:1:22662
> each@https://code.jquery.com/jquery-2.2.4.js:371:10
> c/l.options@https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js:1:22567
> c@https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js:2:2357
> a.fn.datetimepicker/<@https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js:2:2862
> each@https://code.jquery.com/jquery-2.2.4.js:365:10
> each@https://code.jquery.com/jquery-2.2.4.js:137:10
> a.fn.datetimepicker@https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js:2:2725
> window.onload@https://fiddle.jshell.net/_display/:73:1
> "  moment.min.js:6:2834
> 

Where this part is the most important:
> moment construction falls back to js Date()

This is basicalling making that string array to return `new Date('07/11/2017')` which will take the order as Year-Month-Day = 2017-07-11 and not 2017-11-07 what's you're expecting to.

> So what do I do now?

Simple, use moment with the format option as you set it up before `moment('07/11/2017','DD/MM/YYYY')`

If making each of one of the dates to moment to tedious make a function this could help you to start with:

```
var Dates = [
  '08/11/2017',
  '07/11/2017'
];
var enabledDates = [];
Dates.forEach(function(element) {
  enabledDates.push(moment(element, 'DD/MM/YYYY'));
}); 
```

Then just assign that variable to the option a done.

As this is not a bug I'll be closing it.

**Closed by William-H-M** 2017-11-08 15:53 UTC

**Comment by GitzJoey** [comment] 2017-11-08 16:10
yes i understand clearly, its just in the doc, it say accept string which is abit missleading in my opinion. Because from what i read and assume it will accept the string and formatted using the format option.

anyway thanks for the explaination
