### ISSUE TITLE
include build directory in npm module

### ISSUE THREAD

**Issue by sixmen** [Eonasdan/bootstrap-datetimepicker#1022] opened 2015-04-23 05:42 UTC
I want to use bootstrap-datetimepicker with npm, not bower.
But current npm module does not contain build directory.
It's hard to use src/less because I'm using SASS.

Please include the build directory.

**Comment by Eonasdan** [comment] 2015-04-23 13:07
duplicate of #920. This will get changed (again) in the next release

**Closed by Eonasdan** 2015-04-23 13:07 UTC
