### ISSUE TITLE
Dates are being duplicated - Brazilian "Summer Time"

### ISSUE THREAD

**Issue by pinheiroweb** [Eonasdan/bootstrap-datetimepicker#2195] opened 2017-10-16 19:51 UTC
Hello friends,

I'm having a problem with datepicker after the Brazilian "Summer Time" that started on 10/14/2017 here in Brazil.

Dates are being duplicated.

![bug_date](https://user-images.githubusercontent.com/31868978/31631976-3297f0dc-b29a-11e7-9705-18242831954c.jpg)

Can someone help me?
Thanks !

**Comment by William-H-M** [comment] 2017-10-17 00:22
Duplicate of #2182 
You can find there the reason of this and is something that currently is no way to crontol it as each browser decide how to handle DST

**Closed by William-H-M** 2017-10-17 00:22 UTC

**Comment by pinheiroweb** [comment] 2017-10-17 21:23
Hello William,

My team here in Brazil has developed a solution:

We changed the bootstrap-datetimepicker.js file

**function selectDay:** 

selectDay: function (e) {//by giu
                    var day = **moment.utc(viewDate.clone());**
                    if ($(e.target).is('.old')) {
                        day.subtract(1, 'M');
                    }
                    if ($(e.target).is('.new')) {
                        day.add(1, 'M');
                    }
                    setValue(day.date(parseInt($(e.target).text(), 10)));
                    if (!hasTime() && !options.keepOpen && !options.inline) {
                        hide();
                    }
                },

**function fillDate, setting currentDate with utc :**

currentDate = **moment.utc(viewDate.clone()).startOf('M').startOf('w').startOf('d');**


**function fillDow**

fillDow = function () {
                var row = $('<tr>'),
                    currentDate = **moment.utc(viewDate.clone()).startOf('w').startOf('d');**
                **viewDateClone = moment.utc(viewDate.clone());**
                if (options.calendarWeeks === true) {
                    row.append($('<th>').addClass('cw').text('#'));
                }
                while (currentDate.isBefore(**viewDateClone**.endOf('w'))) {
                    row.append($('<th>').addClass('dow').text(currentDate.format('dd')));
                    currentDate.add(1, 'd');
                }
                widget.find('.datepicker-days thead').append(row);
            }
