### ISSUE TITLE
Duplicated in October?

### ISSUE THREAD

**Issue by daniboyBr** [Eonasdan/bootstrap-datetimepicker#2182] opened 2017-09-26 12:44 UTC
In the month of October of any year is repeating a day of the week how do I correct?

**Comment by William-H-M** [comment] 2017-09-26 13:36
Hi, this is a problem of a UTC + 2 If not wrong and has been reported for march too I think.
It's roots are from #881 #1283 and more...
This happen usually for UTC+2 and other 

> Due to daylight saving time in Brazil, moment.js subtracts 1 hour on October. So, 29 October 00:00h becomes October 28 23:00h.

I'll advise you to use the `timeZone`option to deal with it.
https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/docs/Options.md#timezone

There's currently no official fix to it, that's why I advise to use timeZone

**Comment by daniboyBr** [comment] 2017-09-26 14:15
Thanks for responding, but how do I do to insert UTC-3, which would be here from Brazil or let it recognize in a high way. You can give an example as I am new to javascript.

**Comment by William-H-M** [comment] 2017-09-26 15:20
Hi, you could set `timeZone: 'UTC'` the problem with this? is that will show time and date of the UTC and not of your locale, there's not a valid workaround currently for it as said by the people of moment.js
NOTE: you have to add moment-timezone.js for it to work

> To be clear, this is a browser issue - not a moment issue. Similar results can be obtained by just using the Date object. Moment could detect this issue and compensate, but it currently does not.

There's no workaround to it for now, this happens only for Brazil it seems.
https://github.com/moment/moment/issues/2612

The problem is mainly how the browser deal with DST
There's long talks about this:
https://github.com/moment/moment/issues/2618
https://stackoverflow.com/questions/35879043/chrome-and-firefox-exhibit-different-handling-of-an-invalid-dst-time

Sorry If I couldn't be of much help in this case, but this is something that's out of our hands right now.

**Comment by daniboyBr** [comment] 2017-09-26 15:45
How do I use moment.js with no date picker?

**Comment by William-H-M** [comment] 2017-09-26 15:49
Hi, sorry but I do not understand your question.

**Comment by William-H-M** [comment] 2017-10-10 14:11
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.

**Closed by William-H-M** 2017-10-10 14:11 UTC

**Comment by pinheiroweb** [comment] 2017-10-17 21:26
Hello William,

My team here in Brazil has developed a solution:

We have changed the bootstrap-datetimepicker.js file

**function selectDay:** 

selectDay: function (e) {//by giu
                    var day = **moment.utc(viewDate.clone());**
                    if ($(e.target).is('.old')) {
                        day.subtract(1, 'M');
                    }
                    if ($(e.target).is('.new')) {
                        day.add(1, 'M');
                    }
                    setValue(day.date(parseInt($(e.target).text(), 10)));
                    if (!hasTime() && !options.keepOpen && !options.inline) {
                        hide();
                    }
                },

**function fillDate, setting currentDate with utc :**

currentDate = **moment.utc(viewDate.clone()).startOf('M').startOf('w').startOf('d');**


**function fillDow**

fillDow = function () {
                var row = $('<tr>'),
                    currentDate = **moment.utc(viewDate.clone()).startOf('w').startOf('d');**
                **viewDateClone = moment.utc(viewDate.clone());**
                if (options.calendarWeeks === true) {
                    row.append($('<th>').addClass('cw').text('#'));
                }
                while (currentDate.isBefore(**viewDateClone**.endOf('w'))) {
                    row.append($('<th>').addClass('dow').text(currentDate.format('dd')));
                    currentDate.add(1, 'd');
                }
                widget.find('.datepicker-days thead').append(row);
            }

**Comment by William-H-M** [comment] 2017-10-17 21:33
@pinheiroweb has this been tested on various browser like FF or Chrome and on different DST zones?

**Comment by giuice** [comment] 2017-10-19 15:18
# It has been approved now by our test team( @pinheiroweb )

## Setting timezone just for pt-br locale:
```javascript
if (locale == 'pt-br' || locale == 'pt-BR' || locale == '')
            moment.tz.setDefault(moment.tz.guess());
```
## Setting date hour to 12(noon)  in Selectday function:
```javascript
var day =viewDate.clone();
day.set({hour:'12',minute:'00'});
```
## Implementing  utc date compare and operations in fillDate function
```javascript
currentDate = moment.utc(viewDate.clone()).startOf('M').startOf('w').startOf('d'); 
```
## I revert back fillDow function, no need with timezone setted
>Obs.: Using datetimepicker  **version : 4.15.35 .**
