### ISSUE TITLE
format:YYYY-MM，second click display date select

### ISSUE THREAD

**Issue by stevieyu** [Eonasdan/bootstrap-datetimepicker#1894] opened 2016-11-22 06:08 UTC
https://jsfiddle.net/dugujianxiao/ad64awL7/11/
![kapture 2016-11-22 at 14 07 53](https://cloud.githubusercontent.com/assets/8325201/20512848/2304ff14-b0bd-11e6-97ad-09a719c834fd.gif)

**Comment by destinychoice** [comment] 2016-11-22 16:43
im having the exact same issue but with a different format, format is YYYY
		viewMode: 'years',
		format: 'YYYY'

**Comment by stevieyu** [comment] 2016-11-23 03:14
look https://jsfiddle.net/dugujianxiao/ad64awL7/11/

add viewMode
second click display days viewMode

**Comment by underdpt** [comment] 2016-11-23 12:41
Same here. #1897 seems to be a duplicate.

**Comment by stevieyu** [comment] 2016-11-24 02:44
so, That this is a bug?

**Comment by underdpt** [comment] 2016-11-24 17:08
@stevieyu i think it is. If I setup the picker to only show years, it should only show years on every click on the input. Now it shows years on first click, and a full calendar (days, months and years) on second and next clicks.

**Comment by denniskuligin** [comment] 2016-11-28 09:35
@stevieyu yeah it's definitely bug. I have the same bug on some of my projects.
Let's hope they'll fix it asap.

**Comment by mrp14** [comment] 2016-11-29 11:15
+1

**Comment by keegars** [comment] 2016-11-29 11:33
I've got two temporary fixes you can put in place, just done some testing myself as I needed this fixed.

1. Set the input to detect when the datetimepicker is shown, and set the viewmode there, bit lazy, I know.
`$("#elementId").on("dp.show", function(e) {
     $(e.target).data("DateTimePicker").viewMode("months");
})`

2. Alternatively, another fix that works much better. It seems, when the datetimepicker hides/closes. It will set the currentViewMode to 0, which essentially resets it back to days.  If you change this line of code,  on line 937.

`currentViewMode = 0;`
to 
`currentViewMode = minViewModeNumber;`

It will set it to the format when first initialized, and changing the viewMode will work. Do note, it won't go below the format you've specified, so if you've done MM-YYYY, setting viewMode to days won't work as it's lower than months, but I don't see why you'd want to see the days when only showing the month and year.

Hope this helps!

**Comment by ilflask** [comment] 2016-12-23 11:07
I confirm the problem. When will the correction?

**Comment by denniskuligin** [comment] 2016-12-23 12:25
@ilflask you'd read @keegars 's answer. It works pretty well, and still we're agree that a feature should be added ( like minViewModeNumber )

**Comment by pascal-hofmann** [comment] 2017-01-11 10:38
Duplicate of #1854.

**Comment by William-H-M** [comment] 2017-08-17 05:02
Hi, this has been solved on latest version so I'll be closing this

**Closed by William-H-M** 2017-08-17 05:02 UTC
