### ISSUE TITLE
Picker showing seconds-selector when there is an escaped 's' in specified moment format

### ISSUE THREAD

**Issue by niborg** [Eonasdan/bootstrap-datetimepicker#1903] opened 2016-11-28 23:45 UTC
[Fiddle.](https://jsfiddle.net/2wez8f64/1/)

Essentially just trying to display custom text after the date and time per moment's escaping format through the data-date-format attribute. In the fiddle above, the first input shows the seconds selector because there is a lower-case 's' in 'Eastern' -- the second omits the 's' with 'Eatern', and no seconds selector is shown.

Using version 4.7.14, but replicated this on the latest version as well.

**Comment by William-H-M** [comment] 2017-10-03 14:27
Duplicate of #1645

**Closed by William-H-M** 2017-10-03 14:27 UTC
