### ISSUE TITLE
TimePicker component always in 12 hour format if 'a' or 'h' exists as an escaped sequence

### ISSUE THREAD

**Issue by Kelerei** [Eonasdan/bootstrap-datetimepicker#2186] opened 2017-10-03 13:36 UTC
The bootstrap-datetimepicker documentation states that the TimePicker component will display the hours in 12 hour format if 'a' or 'h' exists in the format string.  However, this check should take into account characters that are escaped in format strings (as documented by Moment.js [here](http://momentjs.com/docs/#/displaying/format/)).

By means of example, the format string `D MMMM Y [at] HH:mm` should cause the TimePicker component to display in 24 hour format; even though it contains the 'a' character, the only instance of it occurring is in an escape sequence and therefore should not cause the TimePicker component to display in 12 hour format.  (Conversely, the format string `D MMMM Y [at] h:mm A` *should* cause the TimePicker component to display in 12 hour format, as either 'a' or 'h' occurs outside of an escape sequence.)

A jsfiddle illustrating this can be found at: http://jsfiddle.net/zrkgnwgx/3/

Note: this same issue is mentioned on StackOverflow [here](https://stackoverflow.com/questions/44855204/using-string-literals-in-a-moment-js-dependent-datepicker-messes-up-some-options), though I cannot find any evidence of the StackOverflow poster officially reporting this issue.

**Comment by William-H-M** [comment] 2017-10-03 14:29
Hi, yes this is a bug and seem there's aa ways to solved it as per the PR given on #1645.
I'll be closing this as a duplicate of the same.

**Closed by William-H-M** 2017-10-03 14:29 UTC
