### ISSUE TITLE
Defaultdate from database

### ISSUE THREAD

**Issue by Aramosgr** [Eonasdan/bootstrap-datetimepicker#2010] opened 2017-02-08 11:45 UTC
Hi.

FIrst of all, thanks for this amazing tool.

I'm trying to set defaultDate from a value from a DDBB. The format of this value is DDMMYYYY. I used the same format in the script and also in HTML "data-date-format="DD/MM/YYYY". My problem is that default date understand this data as MMDDYYYY, no matter what I try. I tried to manipulate the data (switching mont for day) and most of the times I got "invalid date", and, the most curious, I managed to fix it with this

$(function () {
var input = '@Html.Raw(Model.dob)'   <-- this is like '02/05/2014'
var dat = new Date(input.substring(6, 10),input.substring(3, 5), input.substring(0, 2))
 $('#datetimepicker1').datetimepicker({
             format: 'DD/MM/YYYY',
             defaultDate: dat
  });

and... I always get it right but with months plus one, for example, 02/05/2015 shows as 02/06/2015

Even if I see my mistake... is there a way to set the format defaultDate expects?

Apologies if I'm wrong and there is a mistake in my code (of course, the most probable).

Thanks in advance.

**Comment by William-H-M** [comment] 2017-02-08 13:26
Hi the problem is the format that comes with the new Date JavaScript just use this solution on the [Fiffle](http://jsfiddle.net/z1235Lq9/)

**Comment by William-H-M** [comment] 2017-09-07 21:02
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.

**Closed by William-H-M** 2017-09-07 21:02 UTC
