### ISSUE TITLE
DatePicker is not clear/reset on button click  

### ISSUE THREAD

**Issue by vatsal9** [Eonasdan/bootstrap-datetimepicker#2088] opened 2017-05-05 06:40 UTC
Hii,

I have used **Eonasdan/bootstrap-datetimepicker version : 4.17.47** in my project. Now i am explaining scenario that i have faced for datetimepicker.
 I have asked [Question](http://stackoverflow.com/questions/43780734/eonasdan-bootstrap-datetimepicker-datetime-picker-reset-through-external-javascr/43781189?noredirect=1#comment74609245_43781189)  in which you will find demo in answer section.

Now coming to scenario,
1) select Date from demo snippet like i am selecting date 02-Feb-2013. 
2) press Clear button 
3) again open calendar 
4) As you show it shows Feb month and year as 2013.

As i want to reset whole calender control on button click so it will look like when we are opening for first time. Is there any event is there? which i can raise on button click?

Please guide me.

**Comment by William-H-M** [comment] 2017-05-05 14:14
Hi, I'm not able to reproduce the error even with the version you specified (on SO is with an old version, 4.15.35 if not wrong)
I made a [fiddle ](https://jsfiddle.net/s4dc2fbj/)to that way I can try it out, not sure but can you test it out, maybe I'm doing something different to you

**Comment by William-H-M** [comment] 2017-08-17 04:41
Hi, I'll be closing this as there's no feedback from original poster, feel free to re open it if need it.

**Closed by William-H-M** 2017-08-17 04:41 UTC
