### ISSUE TITLE
month year picker

### ISSUE THREAD

**Issue by DemetrisLeptos** [Eonasdan/bootstrap-datetimepicker#2139] opened 2017-06-29 18:29 UTC
month year format 'MM/yyyy' simply does not work (smoothly)
first open does not assign value, following selections open in day mode
maybe it's the jquery version

**Comment by William-H-M** [comment] 2017-06-29 19:05
Hi, this is duplicate of the following issues:

#1854
#1894
#1959
quick fix at #1897
And if not wrong this got fixed on last version and on the version 4.17.46 in master branch
This can be close.

**Comment by DemetrisLeptos** [comment] 2017-06-29 19:24
@William-H-M thank you - I've solved it already with a similar method but more general which others could benefit from:

add the data-viewmode attribute
and use like:

        $(document).on(
            'dp.show',
            '[data-viewmode]',
            e => $(e.target).data("DateTimePicker").viewMode($(e.target).attr('data-viewmode')));

**Closed** 2017-06-29 19:37 UTC
