### ISSUE TITLE
Less dependency on npm package to bower

### ISSUE THREAD

**Issue by shawnmclean** [Eonasdan/bootstrap-datetimepicker#1054] opened 2015-05-12 23:32 UTC
When referencing the bower package that is using wiredep on less files, it includes a reference to both:
  1. `/src/less/_bootstrap-datetimepicker.less`
  2. `/src/less/bootstrap-datetimepicker-build.less`

The second file is referencing the bootstrap variables.less file from an npm package [here](https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/less/bootstrap-datetimepicker-build.less#L2). This will throw a less build error for those using bower as some consumers may not be including bootstrap via npm but through bower, such as [bower-bootstrap-less](https://github.com/jozefizso/bower-bootstrap-less). It might be a good idea to change the bootstrap dependency to use bower and include it in the bower.json so consumers can seamlessly reference the dependencies all from bower.

Is there any reason you went with the bootstrap npm package instead of bower?

**Comment by Eonasdan** [comment] 2015-05-12 23:36
duplicate of #920 (and several others), the dev branch will change this

I don't know anything about bower or npm. You guys seems to change your minds every other week about what you want or don't want included.

in the future all changes to package managers except for Nuget will require a PR.

**Closed by Eonasdan** 2015-05-12 23:36 UTC
