### ISSUE TITLE
Default date not working

### ISSUE THREAD

**Issue by evirca** [Eonasdan/bootstrap-datetimepicker#1059] opened 2015-05-14 16:40 UTC
When i set a placeholder on the input, the default data won't be set anymore
https://jsfiddle.net/0Ltv25o8/981/

**Comment by petrot** [comment] 2015-06-05 12:16
See the source:

if (options.defaultDate && input.val().trim() === '' && input.attr('placeholder') === undefined) {
    setValue(options.defaultDate);
}

They check the placeholder, too (I don't knwo why)

**Comment by evirca** [comment] 2015-06-05 12:21
Thanx, I’m asking myself the same question. Maybe because of different browsers behavior on changing value of input from code…

**Comment by petrot** [comment] 2015-06-05 12:23
Now I'm trying to fix this problem: I rename the "placeholder" tag on dialog show and rename back on dialog hide. :)

**Comment by Eonasdan** [comment] 2015-06-08 21:02
the reason we're checking for a placeholder value is so we don't overwrite helper text.

**Comment by YPCrumble** [comment] 2015-06-15 19:49
@Eonasdan would you characterize this as desired behavior or a bug to fix? I'm happy to either write code to get around the placeholder check or (probably more simple) update the docs around `defaultDate` so that people understand the interaction with a placeholder. 

I had the same problem and would have been easier had the docs explained the defaultDate issue if that's helpful.

**Comment by seenimurugan** [comment] 2015-06-25 09:14
I think this is definitely a bug. The default date should take precedence over the placeholder. If no defaultDate provided then placeholder is displayed.

**Comment by asleepypenguin** [comment] 2015-07-09 21:07
I agree with seeimurugan - placeholder shouldn't prevent default from being set.

**Comment by Freezystem** [comment] 2015-08-20 14:52
Same problem here. Spend a lot of time figure out why `defaultDate` won't work.

I don't even understand why the `currentDate` can be set but not the default one. If a date can be set, it could be whatever we want. It doesn't make no sense.

Moreover, I may be wrong but, in my opinion, placeholder isn't linked with the value attribute. The placeholder behavior is handled by the browser, setting or getting the value attribute don't override it.

I think that this issue should be considered as a bug.

**Comment by ricardoespsanto** [comment] 2015-09-15 17:25
Yep, same here, this should be a bug...

**Comment by lasseal** [comment] 2015-09-29 17:11
+1

**Comment by EmersonMellado** [comment] 2016-01-14 14:23
I think it is working now. I am not having the same problem.

**Comment by rohittailor** [comment] 2016-08-24 06:48
Please update doc for defaultDate with placeholder restriction.

We also spent many hours to fix this issue. Finally got this thread and issue is resolved now.

**Comment by emersonmellado** [comment] 2016-08-24 12:15
@rohittailor Can you do a PR?

**Comment by drewlederman** [comment] 2017-08-16 18:25
+1

Spent a fair amount of time trying to figure out why the default date suddenly stopped working.

This behavior is undesirable and should be fixed IMHO.

**Comment by William-H-M** [comment] 2017-08-16 18:48
Hi, @drewlederman this is not an issue on [4.17.47](https://github.com/Eonasdan/bootstrap-datetimepicker/releases/tag/4.17.47) see example here https://jsfiddle.net/William_/20oywuno/4/ so it's not a bug anymore.

Please confirm and when is confirmed, @Eonasdan sorry to bother you again today, but this has been solved on lastest release.

**Comment by Eonasdan** [comment] 2017-08-16 18:53
@William-H-M please send me an email or dm me on twitter

**Closed** 2017-08-16 18:52 UTC
