### ISSUE TITLE
[Help]  input.size is not a function

### ISSUE THREAD

**Issue by KayTokyo** [Eonasdan/bootstrap-datetimepicker#1712] opened 2016-08-02 13:53 UTC
Hi,

I have downloaded the package using bower and added javascript files and css files. When i load the page i get this error in my console

Edit:

I unminified it and the input size is not function is occuring here.

```
        // initializing element and component attributes
        if (element.is('input')) {
            input = element;
        } else {
            input = element.find(options.datepickerInput);
            if (input.size() === 0) {
                input = element.find('input');
            } else if (!input.is('input')) {
                throw new Error('CSS class "' + options.datepickerInput + '" cannot be applied to non input element');
            }
        }
```

```
 g.size is not a function
```

I am using laravel elixer to concat all the files. Here is a list of my js and css files.

```
    mix.scripts([
        bower_components + "moment/min/moment.min.js",
        bower_components + "jquery/dist/jquery.min.js",
        bower_components + "bootstrap/dist/js/bootstrap.min.js",
        bower_components + "eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"
    ], 'public/js/vendor.js');


    mix.styles([
        bower_components + "bootstrap/dist/css/bootstrap.min.css",
        bower_components + "eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css"
    ], 'public/css/vendor.css');
```

In my html layout i have.

```
<!-- Styles -->
<link href="{{ asset('css/vendor.css') }}" rel="stylesheet">
<link href="{{ asset('css/app.css') }}" rel="stylesheet">

<!-- JavaScripts -->
<script src="{{ asset('js/vendor.js') }}"></script>
<script src="{{ asset('js/all.js') }}"></script>
```

and the actual html for the datetime picker.

```
<div class="form-group">
    <div class='input-group date' id='datetimepicker1'>
        <input type='text' class="form-control"/>
        <span class="input-group-addon">
                 <span class="glyphicon glyphicon-calendar"></span>
                  </span>
    </div>
</div>

<script>
    $(document).ready(function() {
        $('#datetimepicker1').datetimepicker();
    });
</script>
```

**Comment by Hobadee** [comment] 2016-08-04 23:37
This is most likely a duplicate of #1714

**Comment by steveyj79** [comment] 2016-08-10 16:06
https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1726 fix is in place

**Comment by Mirigan** [comment] 2016-09-29 15:44
this is still not fixed ?

**Comment by aboobakkar** [comment] 2017-02-07 05:10
yes. this issues still!!

**Comment by osbeug001** [comment] 2017-02-15 10:38
For bower users who are not aware, there is version 4.17.45 which works.

**Closed** 2017-08-18 20:02 UTC
