### ISSUE TITLE
Pressing today button sets time to 00:00 instead of current time

### ISSUE THREAD

**Issue by 00cpxxx** [Eonasdan/bootstrap-datetimepicker#1461] opened 2016-02-13 08:50 UTC
The today button is very useful but when a date and time format is used pressing today will only set the current date, not the time resulting in 00:00. Since the documentation says that it sets the value to "now" I would expect the time to be set too when it is present.

I searched and could not find an opition to enable this and I also search for previous bugs but I didn't find any. I also tried fixing it myself but I did not find the right place to do it.

**Comment by mbilgidhis** [comment] 2016-02-18 14:32
I face the same problem today. After working around a bit, I think the problem is the update. I don't know which update but when I use version : 4.15.35, which is used in the website, current date button works perfectly.

**Comment by comniemeer** [comment] 2016-02-18 21:39
Have the same problem too.
In an older version I used a long time ago (4.0.0-beta) it worked perfectly.

**Comment by SrgSteak** [comment] 2016-02-23 14:46
Can confirm, 4.17.37 sets the time to 00:00, 4.15.35 sets the time to "now".

**Comment by 00cpxxx** [comment] 2016-02-25 17:00
A possible way to fix this is to change the function getMoment from:

```
                if (d === undefined || d === null) {
                    if (tzEnabled) {
                        returnMoment = moment().tz(options.timeZone).startOf('d');
                    } else {
                        returnMoment = moment().startOf('d');
                    }

```
To:

```
                if (d === undefined || d === null) {
                    if (tzEnabled) {
                        returnMoment = moment().tz(options.timeZone).startOf('n');
                    } else {
                        returnMoment = moment().startOf('n');
                    }
```

Since the 'n' formatter returns both date and time while 'd' format returns only date. But I'm not sure of other consequences since this function is used in many other places.

**Comment by mauritsb** [comment] 2016-03-18 10:54
That did not fix for me

**Comment by mauritsb** [comment] 2016-03-18 10:55
I have the same problem, but @00cpxxx 'fix way' did not work for me. any alternation?

**Comment by kyranb** [comment] 2016-05-20 10:45
Any update on a fix for this being merged in?

**Comment by tslatt** [comment] 2016-07-06 13:25
I need this also. Anyone have an answer?

**Closed** 2017-08-28 00:29 UTC
