### ISSUE TITLE
Dates on the right column are "hard to press" on inline mode

### ISSUE THREAD

**Issue by MeLlamoPablo** [Eonasdan/bootstrap-datetimepicker#1137] opened 2015-06-19 12:59 UTC
Hello. I've noticed that on inline forms, the saturday column, or the column at the right, is "hard to press". That means that when hovering the mouse on top of a number and clicking, the date won't be selected unless you click at the very edge of the button.

I've recorded [a video that explains it better](https://www.youtube.com/watch?v=2pBnh2nPLZk).

I've tested it on Google Chrome 43.0.2357.124 m and Mozilla Firefox 37.0.2.

How to reproduce:

* Go to http://eonasdan.github.io/bootstrap-datetimepicker/#inline
* Try to click a date in a column from the right, on its right edge.

Many thanks in advance for your time.

**Comment by Eonasdan** [comment] 2015-06-19 15:55
Yes, this was already brought to my attention. There's a bug in the styles.

I'm working on it.

Thanks for the well done issue :)

duplicate of #1049

**Closed by Eonasdan** 2015-06-19 15:55 UTC
Labels: duplicate
